# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='login.BaseUser')),
                ('person', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='person', to='login.BaseUser')),
            ],
        ),
    ]
