# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-18 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='photo_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
