# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0002_place_author'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.BaseUser')),
                ('place_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='points.Place')),
            ],
        ),
    ]
