# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='place_id',
            new_name='place',
        ),
    ]
