# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0004_auto_20160213_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.BaseUser'),
        ),
    ]
