# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_follower'),
        ('points', '0006_route_routeplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.BaseUser'),
        ),
        migrations.AddField(
            model_name='route',
            name='description',
            field=models.TextField(blank=True, default=b''),
        ),
    ]
