# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-20 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_trip_tripfollower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
